<?php
declare(strict_types = 1);

namespace AW\LeaveRequestBundle\Repository;

/**
 * LeaveRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeaveRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
