version: '2'

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=admin"
      - "MYSQL_DATABASE=leaverequest"

  nginx:
    build: docker/nginx
#      container_name: "poc-sf-rabbitmq.dev"
#      labels:
#        - "traefik.frontend.entryPoints=http"
#        - "traefik.frontend.port=80"
#        - "traefik.frontend.rule=Host:poc-sf-rabbitmq.dev"
    ports:
      - "8092:80"
    links:
      - php
    volumes:
#      - /var/www/html/aw/rmq/poc-sf-rabbitmq/src:/var/www/poc-sf-rabbitmq/src
      - /var/www/html/aw/rmq/poc-sf-rabbitmq:/var/www/poc-sf-rabbitmq

  php:
    image: php:7-fpm
    ports:
      - 9000:9000
    volumes:
      - /var/www/html/aw/rmq/poc-sf-rabbitmq:/var/www/poc-sf-rabbitmq
#      - /var/www/html/aw/rmq/poc-sf-rabbitmq/web:/var/www/poc-sf-rabbitmq/web

    working_dir: /var/www/poc-sf-rabbitmq